### ISSUE TITLE
Example did not work

### ISSUE THREAD

**Issue by wagger301** [thedataincubator/ihtml#1]
I followed the example in the README and got this error:   

 56     application to e.g. generate url or filesystem safe Base64 strings.
     57     """
---> 58     encoded = binascii.b2a_base64(s, newline=False)
     59     if altchars is not None:
     60         assert len(altchars) == 2, repr(altchars)

TypeError: a bytes-like object is required, not 'str'

**Comment by rschroll** [comment]
To help us trace this down, can you help us out on a few questions?

1. What version of Python are you using?
2. What version of Jupyter are you using?
3. What cell produced this error?  Was it the import, or one of the magics?
4. Are there more levels to the traceback?  This particular level doesn't appear to be from our code.
