### ISSUE TITLE
JavaScript error while import ihtml

### ISSUE THREAD

**Issue by kraeml** [thedataincubator/ihtml#2]
When I run this cell once

```python
import ihtml
```
I got this message:
```
Javascript error adding output!
TypeError: IPython.CodeCell.config_defaults is undefined
See your browser Javascript console for more details.
```

When I run the import twice. No error occurred but no javascript is executable in %iframe.

Run with Python 3.5.2
jupyter notebook 5.4.0
jupyter-kernelspec list
Available kernels:
  ruby          /home/vagrant/.local/share/jupyter/kernels/ruby
  bash          /usr/local/share/jupyter/kernels/bash
  javascript    /usr/local/share/jupyter/kernels/javascript
  python3       /usr/local/share/jupyter/kernels/python3
  c             /usr/share/jupyter/kernels/c

pip3 show ihtml
Name: ihtml
Version: 0.1.1
Summary: iframe magic for Jupyter notebooks
Home-page: https://github.com/thedataincubator/ihtml
Author: Robert Schroll
Author-email: robert@thedataincubator.com
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires:

**Comment by rschroll** [comment]
Something's changed in the Javascript objects that the notebook gives us. I know it's breaking the syntax hightlighting, but I didn't know it also broke the execution.  I'll take a look.

**Comment by rschroll** [comment]
I had actually fixed it locally, but hadn't pushed.  Just did that now.  Can you try running the version in master and see if it solve your problem?  Thanks!

**Comment by kraeml** [comment]
Yes it works. Thanks. May you make a new pip version?

**Comment by rschroll** [comment]
Definitely.  Thanks for getting me moving on this!

**Comment by rschroll** [comment]
Version 0.1.2 just went up on pypi with this fix.

**Comment by kraeml** [comment]
Running in my box (ubuntu-1604) via pip. Thanks.
